-- Bloc 6 : leaderboard hebdomadaire + bonus "Joker" (parrainage avant expiration).

-- Journal des récompenses de parrainage (permet de calculer un classement
-- PAR PÉRIODE — "top 3 de la semaine" — impossible avec le seul compteur
-- cumulatif users.paid_referral_count).
create table if not exists referral_rewards (
  id bigint generated by default as identity primary key,
  referrer_telegram_id bigint not null references users (telegram_id),
  referred_telegram_id bigint not null references users (telegram_id),
  bonus_days integer not null,
  milestone_hit boolean not null default false,
  joker_hit boolean not null default false,
  rewarded_at timestamptz not null default now()
);
create index if not exists idx_referral_rewards_referrer_date on referral_rewards (referrer_telegram_id, rewarded_at desc);

-- Gate "un post par semaine" pour le leaderboard public, même principe que
-- lucky_vip_draws pour le tirage quotidien.
create table if not exists leaderboard_posts (
  id bigserial primary key,
  posted_at timestamptz not null default now()
);
create index if not exists idx_leaderboard_posts_date on leaderboard_posts (posted_at desc);
