-- Bloc 3 : Alertes Momentum — contenu d'engagement distinct des vrais signaux
-- (voir signals/momentum.py). Diffusées par le Worker sur le canal public
-- uniquement (cron/dispatchMomentumAlerts.ts), jamais aux abonnés en DM.

create table if not exists momentum_alerts (
  id bigint generated by default as identity primary key,
  pair text not null,
  kind text not null check (kind in ('rsi_neutral_exit', 'ema_cross_unconfirmed', 'atr_spike')),
  detail text not null,
  created_at timestamptz not null default now(),
  sent_to_channel boolean not null default false
);

create index if not exists idx_momentum_alerts_unsent on momentum_alerts (created_at asc) where sent_to_channel = false;
